<?php

/**
 * Implements hook_menu().
 */
function redis_watchdog_menu() {
  $items = [];
  $items['admin/reports/redislog'] = [
    'title' => 'Recent log messages',
    'description' => 'View events that have recently been logged.',
    'page callback' => 'redis_watchdog_overview',
    'access arguments' => ['access site reports'],
    'weight' => -1,
    'file' => 'redis_watchdog.admin.inc',
  ];

  $items['admin/reports/redislog/event/%'] = [
    'title' => 'Details',
    'page callback' => 'redis_watchdog_event',
    'page arguments' => [4],
    'access arguments' => ['access site reports'],
    'file' => 'redis_watchdog.admin.inc',
  ];
  return $items;
}

/**
 * Implements hook_watchdog().
 */
function redis_watchdog_watchdog(array $entry) {
  $q = new Redislog();
  $q->log($entry);
}

/**
 * Private function to return the types of messages stored.
 *
 * @return array|mixed
 */
function _redis_watchdog_get_message_types() {
  $log = new RedisLog();
  return $log->getMessageTypes();
}

/**
 * Implements hook_theme().
 */
function redis_watchdog_theme() {
  return [
    'redis_watchdog_message' => [
      'variables' => ['event' => NULL, 'link' => FALSE],
      'file' => 'redis_watchdog.admin.inc',
    ],
  ];
}
